In [2]:
import duckdb

conn = duckdb.connect('myduck.db')

In [3]:
conn.execute('''
CREATE TABLE tennis_brands (
id INTEGER PRIMARY KEY,
name VARCHAR,
nationality VARCHAR

)

''')

In [4]:
conn.execute("SHOW TABLES").df()

            name
0  tennis_brands

In [5]:
conn.execute('''
INSERT INTO tennis_brands VALUES
(1,'Babolat','French'),
(2,'Wilson','America'),
(3,'Yonex','Japan'),
(4,'Head','Austrian'),
(5, 'Technifibre','French')
''')

In [7]:
conn.execute('SELECT * FROM tennis_brands').df()

   id         name nationality
0   1      Babolat      French
1   2       Wilson     America
2   3        Yonex       Japan
3   4         Head    Austrian
4   5  Technifibre      French

In [8]:
import pandas as pd